INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (1, 'Super Mario Bros', 'NES', 'Platformer', 'Classic Mario adventure');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (2, 'The Legend of Zelda', 'NES', 'Adventure', 'Explore Hyrule');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (3, 'Tetris', 'Game Boy', 'Puzzle', 'Arrange falling blocks');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (4, 'Sonic the Hedgehog', 'Genesis', 'Platformer', 'Speed through zones');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (5, 'Street Fighter II', 'SNES', 'Fighting', 'Fight global opponents');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (6, 'Pokémon Red', 'Game Boy', 'RPG', 'Catch and train Pokémon');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (7, 'Final Fantasy VII', 'PS1', 'RPG', 'Save the planet with Cloud');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (8, 'Metal Gear Solid', 'PS1', 'Stealth', 'Infiltrate enemy base');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (9, 'Resident Evil 2', 'PS1', 'Survival Horror', 'Survive Raccoon City');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (10, 'Halo: Combat Evolved', 'Xbox', 'Shooter', 'Fight the Covenant');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (11, 'The Elder Scrolls V: Skyrim', 'PC', 'RPG', 'Open-world adventure');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (12, 'Minecraft', 'PC', 'Sandbox', 'Build and explore worlds');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (13, 'The Witcher 3', 'PC', 'RPG', 'Hunt monsters as Geralt');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (14, 'Among Us', 'PC', 'Party', 'Find the impostor');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (15, 'Celeste', 'PC', 'Platformer', 'Climb the mountain');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (16, 'Hollow Knight', 'PC', 'Metroidvania', 'Explore Hallownest');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (17, 'DOOM Eternal', 'PC', 'Shooter', 'Rip and tear demons');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (18, 'Hades', 'PC', 'Roguelike', 'Escape the Underworld');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (19, 'Cuphead', 'PC', 'Run and Gun', 'Defeat bosses');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (20, 'Stardew Valley', 'PC', 'Simulation', 'Manage a farm');
INSERT INTO Games (Id, Title, Platform, Genre, Description) VALUES (21, 'Animal Crossing: New Horizons', 'Switch', 'Simulation', 'Build your island');

INSERT INTO UserGameCollections (Id, GameId, User) VALUES (1, 1, 'juanma');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (2, 3, 'juanma');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (3, 5, 'juanma');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (4, 7, 'maria87');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (5, 8, 'maria87');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (6, 2, 'gamerpro');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (7, 4, 'gamerpro');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (8, 6, 'retrofan');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (9, 9, 'retrofan');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (10, 10, 'admin');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (11, 11, 'admin');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (12, 12, 'testuser');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (13, 13, 'testuser');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (14, 14, 'sofia');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (15, 15, 'sofia');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (16, 16, 'lucas');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (17, 17, 'lucas');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (18, 18, 'noelia');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (19, 19, 'noelia');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (20, 20, 'david');
INSERT INTO UserGameCollections (Id, GameId, User) VALUES (21, 21, 'david');
